import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const libRoot = join(root, 'lib');
const channelSource = join(root, 'channel', 'source');
const outFile = join(channelSource, 'DuplexShared.brs');

const ORDER = [
  'platform/BuildConfig.brs',
  'platform/KeyNormalize.brs',
  'platform/RegistryStore.brs',
  'platform/DeviceIdentity.brs',
  'platform/Locale.brs',
  'api/AuthService.brs',
  'api/GraphqlClient.brs',
  'api/RestClient.brs',
  'services/Formatters.brs',
  'services/DeviceService.brs',
  'services/PlaylistService.brs',
  'services/PrepareService.brs',
  'services/ContentService.brs',
  'services/ContentCache.brs',
  'services/FavoritesService.brs',
  'services/ParentalService.brs',
  'services/WatchHistoryService.brs',
  'services/SettingsService.brs',
  'core/ScreenIds.brs',
  'core/Session.brs',
];

function listBrs(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      out.push(...listBrs(full));
    } else if (name.endsWith('.brs')) {
      out.push(relative(libRoot, full).split('\\').join('/'));
    }
  }
  return out;
}

const found = listBrs(libRoot).filter((rel) => rel !== 'keyboard/DuplexKeyboard.brs');
const missing = ORDER.filter((rel) => !found.includes(rel));
const extra = found.filter((rel) => !ORDER.includes(rel));
if (missing.length > 0 || extra.length > 0) {
  console.error('lib/ BrightScript files do not match ORDER in tools/build-lib.mjs');
  if (missing.length > 0) console.error('  missing from lib/:', missing.join(', '));
  if (extra.length > 0) console.error('  add to ORDER:', extra.join(', '));
  process.exit(1);
}

const parts = [
  "' Auto-generated by tools/build-lib.mjs — do not edit.",
  "' Edit modules under lib/{platform,api,services,core}/ then run npm run build:lib.",
  '',
];

for (const rel of ORDER) {
  const body = readFileSync(join(libRoot, rel), 'utf8').trim();
  parts.push(`' ===== ${rel} =====`);
  parts.push(body);
  parts.push('');
}

mkdirSync(channelSource, { recursive: true });
writeFileSync(outFile, `${parts.join('\n')}\n`);

const keyboardDir = join(channelSource, 'widgets');
mkdirSync(keyboardDir, { recursive: true });
const keyboard = readFileSync(join(libRoot, 'keyboard', 'DuplexKeyboard.brs'), 'utf8').trim();
writeFileSync(
  join(keyboardDir, 'DuplexKeyboard.brs'),
  `' Auto-generated copy of lib/keyboard/DuplexKeyboard.brs — do not edit.\n\n${keyboard}\n`,
);

console.log(`Built channel/source/DuplexShared.brs from ${ORDER.length} modules`);
